### ISSUE TITLE
x64 build crashes everytime I press F9

### ISSUE THREAD

**Issue by Ripley63** [orbitersim/orbiter#311] opened 2022-11-24 13:28 UTC
...Or if I check the corresponding box in the Options window -> Planetarium.

[Logs_Orbiter-x64.zip](https://github.com/orbitersim/orbiter/files/10084907/Logs_Orbiter-x64.zip)

While reading the log, I noticed that the new PlanetTexDir entry is not logged.

**Comment by parzival2** [comment] 2022-11-25 08:30
Can confirm. Happens to me too. But the problem is that it doesnt happen in Release build or the one that we download from github releases. In debug it happens every time.

**Comment by mschweiger** [comment] 2022-11-25 22:41
I can't reproduce this crash in either release or debug builds, so it would help if you could debug it for me. Thanks!

**Comment by Ripley63** [comment] 2022-11-26 09:17
I'm not at my pc now.
I wrote "build" in the title, but now I don't know if it's correct.
What I downloaded and tested are the x86/x64 zip files under "Assets".

The 3 or 4 previous versions I tried never showed this bug.

Il ven 25 nov 2022, 23:41 mschweiger ***@***.***> ha scritto:

**Comment by parzival2** [comment] 2022-11-26 09:18
Ok that's unfortunate. I am still new to the code but I will try to debug to the best of my abilities Dr. Schweiger.

**Comment by mschweiger** [comment] 2022-11-26 15:51
- Add line `Planetarium = 0` to OrbiterNG.cfg. This will turn off all planetarium elements.
- Check that Ctrl-F9 no longer crashes
- If that works, open the planetarium configuration page (F6 | Planetarium) and turn on elements one by one until the crash happens. Since the last thing added were the grid labels, I suspect that turning on any of the grids should trigger the crash.
- Once you have a minimum configuration that consistently crashes, put a breakpoint at the beginning of `D3D9CelestialSphere::Render` and try to locate the offending statement or the system call that doesn't return.

**Comment by parzival2** [comment] 2022-11-26 15:55
> - Add line `Planetarium = 0` to OrbiterNG.cfg. This will turn off all planetarium elements.
> - Check that Ctrl-F9 no longer crashes
> - If that works, open the planetarium configuration page (F6 | Planetarium) and turn on elements one by one until the crash happens. Since the last thing added were the grid labels, I suspect that turning on any of the grids should trigger the crash.
> - Once you have a minimum configuration that consistently crashes, put a breakpoint at the beginning of `D3D9CelestialSphere::Render`, step through it and try to locate the offending statement or the system call that doesn't return.

Thank you very much for the detailed debugging instructions Dr. Schweiger. Will debug and figure out what might be causing the problem.

**Comment by Ripley63** [comment] 2022-11-27 21:49
After setting Planetarium=0, I can confirm that enabling any of the grids always crashes Orbiterx64 (and Orbiterx86, only in D3D9).

**Comment by mschweiger** [comment] 2022-11-28 00:27
OK. Are you in a position to debug (or at least compile) the code?

**Comment by mschweiger** [comment] 2022-11-28 00:56
Also, I just noticed from the log file you posted that you have redirected your TextureDir and HightexDir locations. Any particular reason for this? For the development builds this is probably not a good idea since you will be missing any additional textures added during development. If you didn't copy the new gridlabel.dds file from the local Textures directory to your Orbiter2016\Textures directory, it will not be found, which may well be the reason for the crash. What happens if you don't redirect these folder locations?

The only directory that _should_ be redirected is the PlanetTexDir folder, since that doesn't exist in the development build.

**Comment by mschweiger** [comment] 2022-11-28 02:21
I have now pushed a PR to main which should deal with a missing grid label texture file more gracefully. Instead of crashing, it should just not display the labels and leave an error message in the log file instead. Does this make any difference to the observed behaviour for both of you?

**Comment by parzival2** [comment] 2022-11-28 11:27
_The only directory that should be redirected is the PlanetTexDir folder, since that doesn't exist in the development build._
I guess I did this mistake and by only redirecting `PlanetTexDir` the issue seems to be solved on my side even on the debug builds. Sorry for the late reply Dr. Schweiger

**Comment by Ripley63** [comment] 2022-11-28 11:39
> Also, I just noticed from the log file you posted that you have redirected your TextureDir and HightexDir locations.

That was it! Redirecting only PlaneTexDir and leaving the other dirs at their default results in NO crashes whatsoever.
Thanks and sorry for my misleasding bug report.

**Comment by mschweiger** [comment] 2022-11-28 15:57
Thanks for the feedback. Can you also confirm that with the latest build you don't get crashes anymore even if you still redirect the TextureDir and HightexDir locations?

**Comment by Ripley63** [comment] 2022-11-28 19:20
Yes, confirmed, no more crashes with textures dirs redirection, both x86 and x64, BUT now solar panels flicker when in external visuals (default DG docked at ISS scenario).

**Comment by mschweiger** [comment] 2022-11-28 22:05
Sorry, are you saying that this latest problem has only started happening with the latest commit ([111577b](https://github.com/orbitersim/orbiter/commit/111577ba0c5029f36c0aa7f1bcb111e1ab9a25ca)) and only if you redirect TextureDir and HighTexDir? 

If that isn't what you are saying, can you please open another issue for that problem, since it doesn't seem to be connected to what was discussed here so far. Also, please provide as much details as possible (which clients, which screen modes, and ideally the commit hash when this started to happen). Thanks!

**Comment by Ripley63** [comment] 2022-11-29 09:34
Hi, the new dawn took the flickering away.
No flickering whatsoever in ext visuals now, redirecting one texture dir at the time.
Must have been an error on my side, sorry for my crappy bugreport.

**Comment by mschweiger** [comment] 2022-11-29 23:36
No worries. Closing this issue.

**Closed by mschweiger** 2022-11-29 23:36 UTC
